version: "3.9"

services:
  haproxy:
    image: haproxy:2.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./certs:/usr/local/etc/haproxy/certs
    depends_on:
      - nginx1
      - nginx2
      - nginx3
    networks:
      - wp-network

  wordpress1:
    build: ./php
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./wordpress1-html:/var/www/html
    networks:
      - wp-network

  nginx1:
    image: nginx:1.25
    depends_on:
      - wordpress1
    volumes:
      - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress1-html:/var/www/html
    networks:
      - wp-network

  wordpress2:
    build: ./php
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./wordpress2-html:/var/www/html
    networks:
      - wp-network

  nginx2:
    image: nginx:1.25
    depends_on:
      - wordpress2
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress2-html:/var/www/html
    networks:
      - wp-network

  wordpress3:
    build: ./php
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./wordpress3-html:/var/www/html
    networks:
      - wp-network

  nginx3:
    image: nginx:1.25
    depends_on:
      - wordpress3
    volumes:
      - ./nginx/nginx3.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress3-html:/var/www/html
    networks:
      - wp-network

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wp-network

volumes:
  mariadb-data:
  wordpress1-html:
  wordpress2-html:
  wordpress3-html:

networks:
  wp-network:

