all:
  children:
    ethereum_nodes:
      hosts:
        eth-node:
          ansible_host: 10.7.14.38
          ansible_user: batya
          #ansible_ssh_private_key_file: ~/.ssh/key.pem
          ansible_python_interpreter: /usr/bin/python3.10
