apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: wp-stack
data:
  haproxy.cfg: |
    global
        log stdout format raw local0
        maxconn 2000
        tune.ssl.default-dh-param 2048

    defaults
        log global
        mode http
        option httplog
        option dontlognull
        timeout connect 5000ms
        timeout client  50000ms
        timeout server  50000ms

    resolvers kube-dns
        nameserver kube-dns 10.96.0.10:53
        resolve_retries       3
        timeout resolve       1s
        timeout retry         1s
        hold valid           10s

    frontend https-in
        bind *:443 ssl crt /etc/haproxy/certs/tls.pem
        mode http
        default_backend nginx_servers

    frontend http-in
        bind *:80
        mode http
        redirect scheme https code 301 if !{ ssl_fc }

    backend nginx_servers
        mode http
        balance roundrobin
        option httpchk GET /
        server-template nginx 3 nginx-phpfpm.wp-stack.svc.cluster.local:443 check ssl verify none resolvers kube-dns resolve-prefer ipv4

