apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: wp-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:2.8
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: haproxy-config-volume
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
          subPath: haproxy.cfg
        - name: haproxy-certs
          mountPath: /etc/haproxy/certs
      volumes:
      - name: haproxy-config-volume
        configMap:
          name: haproxy-config
      - name: haproxy-certs
        secret:
          secretName: tls-secret

