#all:
  #children:
   # core_switches:
   #   hosts:
    #    core-sw01:
     #     ansible_host: 10.7.5.110
      #    ansible_user: admin
       #   ansible_ssh_pass: "1qa2ws)OK(IJ"
        #  ansible_network_os: nxos
all:
  children:
    core_switches:
      hosts:
        core-sw01:
          ansible_host: 10.7.5.110
          ansible_user: admin
          ansible_password: "*********"
          ansible_network_os: nxos
          ansible_connection: network_cli
          ansible_become: yes
          ansible_become_method: enable
          ansible_become_password: "1qa2ws)OK(IJ"

        core-sw02:
          ansible_host: 10.7.5.111
          ansible_user: admin
          ansible_password: "*********"
          ansible_network_os: nxos
          ansible_connection: network_cli
          ansible_become: yes
          ansible_become_method: enable
          ansible_become_password: "1qa2ws)OK(IJ"
